### ISSUE TITLE
BIOS changes

### ISSUE THREAD

**Issue by ghost** [onetown/gigabyte-z390-aorus-elite-hackintosh-opencore#1]
What is the change in your BIOS?

**Comment by onetown** [comment]
I know It's been a long time, I haven't pay a lot attention to this repo, maybe you already figured out how to setup an opencore or gave it up, lol. 

I actually didn't change a lot in BIOS, you should install a pure MacOS without any problem with this config. although, you still need set model to MacPro, but if you met any challenge, try to set:
1. Disable CSM support
2. Disable fast boot
